---
- name: "untar"
  unarchive:
    src: "{{ dest_tarfile }}"
    dest: "{{ destination }}"

- name: Set Java HOME
  lineinfile: 
   dest=~/.bashrc 
   regexp='^JAVA_HOME'>
   line='export JAVA_HOME="{{java_name}}"'
- name: Set JAVA PATH
  lineinfile: 
   dest=~/.bashrc regexp='^JAVA_HOME'>
   line="export PATH=$PATH:$JAVA_hOME/bin"

